baseURL = "https://kkobau.com/"
languageCode = "en-us"
title = "Klemen Kobau - Developer Blog"
theme = "PaperMod"

[params]
  author = "Klemen Kobau"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
  Title = "Klemen Kobau"
  Content = "Developer blog showcasing programming projects"

[[params.socialIcons]]
  name = "cv"
  url = "https://klemenkobau.gitlab.io/cv/klemen-kobau.pdf"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/KlemenKobau"

[[params.socialIcons]]
  name = "gitlab"
  url = "https://gitlab.com/KlemenKobau"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/klemen-kobau/"

[[params.socialIcons]]
  name = "email"
  url = "mailto:klemen.kobau@gmail.com"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'
